[build-system]
requires = [
   "setuptools>=42",
   "wheel",
   "cmake>=3.24",
]
build-backend = "setuptools.build_meta"

[project]
name = "BPOTF"

description = "BPOTF: Implementation of Belief Propagation Ordered Tanner Forest decoding method."
readme = "README.md"
authors = [
   { name = "Antonio de Martì i Olius", email = "ademartio@unav.es" },
   { name = "Josu Etxezarreta Martinez", email = "jetxezarreta@unav.es" },
   { name = "Joschka Roffe", email = "joschka@roffe.eu" },
   { name = "Imanol Etxezarreta Martinez", email = "ietxezarretam@gmail.com" }
]
license = { file = "LICENSE" }

requires-python = ">=3.8"
dependencies = [
   "scipy",
   "stim",
   "sinter",
   "numpy",
   "ldpc"
]
dynamic = ["version"]

[project.urls]
"Source Code" = "https://github.com/Ima96/BPOTF"

[tool.setuptools.packages.find]
where = ["src"]  
include = ["BPOTF"]

[tool.distutils.egg_info]
egg_base = "build"
